### ISSUE TITLE
Net framework 4.5

### ISSUE THREAD

**Issue by Lechus** [alex75it/JSON-Tree-Viewer#1]
Hi,
Could you downgrade Net Framework required to 4.5.2 so it could be installed in older apps?

Thank you.

**Comment by alex-piccione** [comment]
Hi,
I have a Windows Form project to test the library.
I changed the .Net Framework of that project to 4.5.2 (It was 4.6.1 as the library itself).
The project references the library and needs Newtonsoft.Json.

It runs without problems, Newtonsoft.JSON and the library are both referenced using NuGet and this is the package.config:
``` xml
<packages>
  <package id="Alex75.JsonViewer" version="0.2.6174.32328" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
</packages>
```
![Net 4 5 2 compatibility](https://user-images.githubusercontent.com/876490/63797374-dfe42f80-c8ff-11e9-91ac-fa4c2900c571.png)

I hope this solve your case.

Alex

**Comment by Lechus** [comment]
Yes, can change config to 452, but does not work when using nuget package.
Found other solution, so not a problem anymore.
Cheers
